#############################################################################
# Makefile for building: SWipe.app/Contents/MacOS/SWipe
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  SWipe.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile SWipe.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.10.1/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SWipe1.0.0
DISTDIR = /Users/Vanze/SWipe/.tmp/SWipe1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.10.1/lib -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		swipe.cpp \
		magdecode.cpp \
		mslib.c \
		llist.c \
		carddetect.cpp moc_swipe.cpp \
		moc_magdecode.cpp
OBJECTS       = main.o \
		swipe.o \
		magdecode.o \
		mslib.o \
		llist.o \
		carddetect.o \
		moc_swipe.o \
		moc_magdecode.o
DIST          = /usr/local/Cellar/qt/5.10.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/lex.prf \
		SWipe.pro swipe.h \
		magdecode.h \
		mslib.h \
		llist.h \
		carddetect.h \
		magcard.h main.cpp \
		swipe.cpp \
		magdecode.cpp \
		mslib.c \
		llist.c \
		carddetect.cpp
QMAKE_TARGET  = SWipe
DESTDIR       = 
TARGET        = SWipe.app/Contents/MacOS/SWipe

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d SWipe.app/Contents/MacOS/ || mkdir -p SWipe.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SWipe.pro /usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.10.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.10.1/mkspecs/features/lex.prf \
		SWipe.pro \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/QtMultimedia.prl \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/QtNetwork.prl \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile SWipe.pro
/usr/local/Cellar/qt/5.10.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.10.1/mkspecs/features/lex.prf:
SWipe.pro:
/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/QtMultimedia.prl:
/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/QtNetwork.prl:
/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SWipe.pro

qmake_all: FORCE

SWipe.app/Contents/PkgInfo: 
	@test -d SWipe.app/Contents || mkdir -p SWipe.app/Contents
	@$(DEL_FILE) SWipe.app/Contents/PkgInfo
	@echo "APPL????" > SWipe.app/Contents/PkgInfo
SWipe.app/Contents/Resources/empty.lproj: 
	@test -d SWipe.app/Contents/Resources || mkdir -p SWipe.app/Contents/Resources
	@touch SWipe.app/Contents/Resources/empty.lproj
	
SWipe.app/Contents/Info.plist: 
	@test -d SWipe.app/Contents || mkdir -p SWipe.app/Contents
	@$(DEL_FILE) SWipe.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,sharemeals.SWipe,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},sharemeals.SWipe,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.10,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,SWipe,g" -e "s,@LIBRARY@,SWipe,g" -e "s,\$${EXECUTABLE_NAME},SWipe,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang/Info.plist.app >SWipe.app/Contents/Info.plist

all: Makefile \
		SWipe.app/Contents/PkgInfo \
		SWipe.app/Contents/Resources/empty.lproj \
		SWipe.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.10.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents swipe.h magdecode.h mslib.h llist.h carddetect.h magcard.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp swipe.cpp magdecode.cpp mslib.c llist.c carddetect.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r SWipe.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.10.1/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.10.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_swipe.cpp moc_magdecode.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_swipe.cpp moc_magdecode.cpp
moc_swipe.cpp: /usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers/QAudioInput \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers/qaudioinput.h \
		magdecode.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QIODevice \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QVarLengthArray \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		mslib.h \
		llist.h \
		magcard.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdatetime.h \
		carddetect.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qmap.h \
		swipe.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.10.1/bin/moc
	/usr/local/Cellar/qt/5.10.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang -I/Users/Vanze/SWipe -I/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.10.1/lib swipe.h -o moc_swipe.cpp

moc_magdecode.cpp: /usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QIODevice \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QVarLengthArray \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		mslib.h \
		llist.h \
		magcard.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdatetime.h \
		magdecode.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.10.1/bin/moc
	/usr/local/Cellar/qt/5.10.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang -I/Users/Vanze/SWipe -I/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.10.1/lib magdecode.h -o moc_magdecode.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp swipe.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers/QAudioInput \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers/qaudioinput.h \
		magdecode.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QIODevice \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QVarLengthArray \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		mslib.h \
		llist.h \
		magcard.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdatetime.h \
		carddetect.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

swipe.o: swipe.cpp swipe.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers/QAudioInput \
		/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers/qaudioinput.h \
		magdecode.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QIODevice \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QVarLengthArray \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		mslib.h \
		llist.h \
		magcard.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdatetime.h \
		carddetect.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swipe.o swipe.cpp

magdecode.o: magdecode.cpp magdecode.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QIODevice \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QVarLengthArray \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		mslib.h \
		llist.h \
		magcard.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o magdecode.o magdecode.cpp

mslib.o: mslib.c mslib.h \
		llist.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mslib.o mslib.c

llist.o: llist.c llist.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o llist.o llist.c

carddetect.o: carddetect.cpp carddetect.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qmap.h \
		magcard.h \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers/qdatetime.h \
		mslib.h \
		llist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carddetect.o carddetect.cpp

moc_swipe.o: moc_swipe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_swipe.o moc_swipe.cpp

moc_magdecode.o: moc_magdecode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_magdecode.o moc_magdecode.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

